steps:
  #
  # Run setup
  #
  # 1. setup things, including firebase-tools in package.json
  - name: "nikolaik/python-nodejs:latest"
    entrypoint: yarn
    args: ["install"]
    dir: "frontend"

    # 2. run prerun
  - name: "nikolaik/python-nodejs:latest"
    entrypoint: yarn
    args: ["prerun"]
    env:
      - "BUILD_CTX=cloud-build"
      - "TAG_NAME=$TAG_NAME"
      - "SHORT_SHA=$SHORT_SHA"
    dir: "frontend"

    #
    # Deploy to Firebase
    #
    #  from https://dev.to/leomercier/deploying-a-gatsby-site-to-firebase-with-google-cloud-build-ci-cd-511c
    #  token from https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/firebase
    #
    # 1. export static files from sapper
  - name: "nikolaik/python-nodejs:latest"
    entrypoint: yarn
    args: ["export:only"]
    dir: "frontend"

    # 2. deploy files to firebase
  - name: "nikolaik/python-nodejs:latest"
    entrypoint: "./node_modules/.bin/firebase"
    args:
      ["deploy", "--project", "personal-c913b", "--token", "$_FIREBASE_TOKEN"]
    dir: "frontend"

    #
    # Deploy to Cloud Run
    #
    # 1. build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/personal-c913b/personal-website", "."]
    dir: "frontend"

    # 2. push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/personal-c913b/personal-website"]
    dir: "frontend"

    # 3. Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "personal-website",
        "--image",
        "gcr.io/personal-c913b/personal-website",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--quiet",
      ]
    dir: "frontend"

images:
  - gcr.io/personal-c913b/personal-website

artifacts:
  objects:
    location: gs://jeffjose-personal-website/
    paths: ["blog/index-blog.yaml", "books/index-books.yaml", "meta.json"]
