steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/personal-c913b/personal-website', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/personal-c913b/personal-website']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'personal-website', '--image', 'gcr.io/personal-c913b/personal-website', '--region', 'us-central1','--platform', 'managed', '--quiet']
images:
- gcr.io/personal-c913b/personal-website
